const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  minimize: () => ipcRenderer.send('win:minimize'),
  focusWin: () => ipcRenderer.send('win:focus'),
  nativeNotify: (p) => ipcRenderer.send('notify:native', p),
  onRelayOpen: (cb) => ipcRenderer.on('relay:open', (_e, nick) => cb(nick)),
  maximize: () => ipcRenderer.send('win:maximize'),
  close: () => ipcRenderer.send('win:close'),
  openExternal: (url) => ipcRenderer.send('open-external', url),
  version: () => ipcRenderer.invoke('app:version'),
  getConfig: () => ipcRenderer.invoke('config:get'),
  setConfig: (patch) => ipcRenderer.invoke('config:set', patch),
  openFolder: () => ipcRenderer.invoke('config:openFolder'),
  serverStatus: () => ipcRenderer.invoke('server:status'),
  play: (opts) => ipcRenderer.invoke('game:play', opts),
  installUpdate: () => ipcRenderer.invoke('app:installUpdate'),
  listShots: () => ipcRenderer.invoke('shots:list'),
  deleteShot: (p) => ipcRenderer.invoke('shots:delete', p),
  openShot: (p) => ipcRenderer.invoke('shots:open', p),
  copyShot: (p) => ipcRenderer.invoke('shots:copy', p),
  openShotsFolder: () => ipcRenderer.invoke('shots:openFolder'),
  saveSkin: (p) => ipcRenderer.invoke('skins:save', p),
  listSkins: () => ipcRenderer.invoke('skins:list'),
  setSkin: (id) => ipcRenderer.invoke('skins:set', id),
  deleteSkin: (id) => ipcRenderer.invoke('skins:delete', id),
  favSkin: (p) => ipcRenderer.invoke('skins:fav', p),
  listMods: () => ipcRenderer.invoke('mods:list'),
  listOMods: () => ipcRenderer.invoke('omods:list'),
  toggleOMod: (p) => ipcRenderer.invoke('omods:toggle', p),
  removeOMod: (id) => ipcRenderer.invoke('omods:remove', id),
  searchModrinth: (q) => ipcRenderer.invoke('omods:search', q),
  addModrinthMod: (p) => ipcRenderer.invoke('omods:addModrinth', p),
  addLocalMod: (p) => ipcRenderer.invoke('omods:addLocal', p),
  discordStatus: () => ipcRenderer.invoke('discord:status'),
  newsList: () => ipcRenderer.invoke('news:list'),
  submitShot: (p) => ipcRenderer.invoke('gallery:submit', p),
  featuredGallery: () => ipcRenderer.invoke('gallery:featured'),
  voteShot: (p) => ipcRenderer.invoke('gallery:vote', p),
  authState: () => ipcRenderer.invoke('auth:state'),
  authLogin: (p) => ipcRenderer.invoke('auth:login', p),
  authLogout: () => ipcRenderer.invoke('auth:logout'),
  friendsList: () => ipcRenderer.invoke('friends:list'),
  friendRequest: (to) => ipcRenderer.invoke('friends:request', to),
  friendRespond: (p) => ipcRenderer.invoke('friends:respond', p),
  friendCancel: (id) => ipcRenderer.invoke('friends:cancel', id),
  friendRemove: (nick) => ipcRenderer.invoke('friends:remove', nick),
  shopData: () => ipcRenderer.invoke('shop:data'),
  shopPurchase: (p) => ipcRenderer.invoke('shop:purchase', p),
  chatInbox: () => ipcRenderer.invoke('chat:inbox'),
  chatHistory: (p) => ipcRenderer.invoke('chat:history', p),
  chatSend: (p) => ipcRenderer.invoke('chat:send', p),
  chatSendImage: (p) => ipcRenderer.invoke('chat:sendImage', p),
  onLog: (cb) => ipcRenderer.on('mc:log', (_e, m) => cb(m)),
  onProgress: (cb) => ipcRenderer.on('mc:progress', (_e, p) => cb(p)),
  onDownload: (cb) => ipcRenderer.on('mc:download', (_e, d) => cb(d)),
  onLaunched: (cb) => ipcRenderer.on('mc:launched', () => cb()),
  onClosed: (cb) => ipcRenderer.on('mc:closed', (_e, c) => cb(c)),
  onUpdate: (cb) => ipcRenderer.on('app:update', (_e, u) => cb(u)),
});
