name: Greetings

on: [issues, pull_request_target]

permissions:
  contents: read

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@3c71ce730280171fd1cfb57c00c774f8998586f7 # v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Thanks for the report! Staff will take a look - for faster help you can also ping us on the [MC Tema Discord](https://discord.gg/mctema).'
          pr-message: 'Thanks for the contribution! Please make sure CI passes and the checklist in the PR description is done.'
