name: Greetings

on: [issues, pull_request_target]

permissions:
  contents: read

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@1c4688942c71f71d4f5502a26ea67c331730fa4d # v3.1.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          issue_message: 'Thanks for the report! Staff will take a look - for faster help you can also ping us on the [MC Tema Discord](https://discord.gg/mctema).'
          pr_message: 'Thanks for the contribution! Please make sure CI passes and the checklist in the PR description is done.'
