name: Stale issues

on:
  schedule:
    - cron: '0 5 * * *'

permissions:
  contents: read

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9
        with:
          days-before-stale: 45
          days-before-close: 14
          stale-issue-message: 'No activity for 45 days - closing in 14 days unless there is an update.'
          stale-pr-message: 'No activity for 45 days - closing in 14 days unless there is an update.'
          exempt-issue-labels: 'pinned,security'
